DROP TABLE IF EXISTS Test.Person;

CREATE TABLE Test.Person
(
    PersonID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [NAME] NVARCHAR(64) NOT NULL UNIQUE,
    Age INT NOT NULL,
    Birthdate DATETIME NOT NULL
)

SELECT *
FROM Test.Person